import {
  BadgeCheck,
  BarChart3,
  BriefcaseBusiness,
  CalendarDays,
  ChartLine,
  CirclePlus,
  CreditCard,
  Gift,
  IdCard,
  LayoutDashboard,
  ListTodo,
  MessageCircle,
  Package,
  RotateCcw,
  Rss,
  Settings,
  Share2,
  ShieldCheck,
  Star,
  Store,
  UserPlus,
  Users,
  UsersRound,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const dashboardIconMap: Record<string, LucideIcon> = {
  "badge-check": BadgeCheck,
  "bar-chart-3": BarChart3,
  "briefcase-business": BriefcaseBusiness,
  "calendar-days": CalendarDays,
  "chart-line": ChartLine,
  "circle-plus": CirclePlus,
  "credit-card": CreditCard,
  gift: Gift,
  "id-card": IdCard,
  "layout-dashboard": LayoutDashboard,
  "list-todo": ListTodo,
  "message-circle": MessageCircle,
  package: Package,
  "rotate-ccw": RotateCcw,
  rss: Rss,
  settings: Settings,
  "share-2": Share2,
  "shield-check": ShieldCheck,
  star: Star,
  store: Store,
  "user-plus": UserPlus,
  users: Users,
  "users-round": UsersRound,
};

export const getDashboardIcon = (name: string): LucideIcon =>
  dashboardIconMap[name] ?? ListTodo;
